### ISSUE TITLE
CSS Selector instead ElementReference

### ISSUE THREAD

**Issue by Liero** [KristofferStrube/Blazor.Popper#3]
Hi,

In some scenarios, e.g. #2, it would be very convenient if we could just pass a css selector instead ElementRef:

```csharp
string referenceSelector = $"[data-index={Index}]";
string popperReference = "#popover";
await Popper.CreatePopperAsync(referenceSelector, popperReference, new());
```
Theoretically it could go event further, so to that we scope the css selector to particular component
```csharp
ElementReference rootElement; 
string referenceSelector = $"[data-index={Index}]";
string popperReference = "#popover";
await Popper.CreatePopperAsync(rootElement, referenceSelector, popperReference, new());
//js: let reference = rootElement.querySelector(referenceSelector);
```

**Comment by KristofferStrube** [comment]
Interesting idea.

What would happen if the CSS-selector would find multiple elements fitting the descriptor? If it were to make Poppers for multiple references then we would need to return a list of Popper `Instance`'s instead, but it's definitely possible.

A workaround for this would be to make a small JS Interop that simply selects using the CSS selector and then returns a list of `ElementReference`'s where we could then initialize a Popper for each of these in the C# code.

Another problem is that you would need a tooltip element for each popper anyway as it cannot be shared between multiple poppers that are active at the same time.

I see the pain, but I think it would be better to use the existing concepts in Blazor (like components) instead of solving it with more JS Interop.

**Comment by Liero** [comment]
well, why don't just use `document.QuerySelector(..)`, resp HtmlElement.QuerySelector(..) that always matches just single element. 

It's quite common approach used for example in bootstrap components defined via attributes, e.g
`data-toggle="collapse"  data-target="parent | cssSelector"`

https://getbootstrap.com/docs/4.6/components/collapse/#via-data-attributes:

> The data-target attribute accepts a CSS selector to apply the collapse to

Of course, if you think this is not such a great idea, feel free to close the issue with 'Won't fix'

**Comment by KristofferStrube** [comment]
I would be interested in being able to add poppers more easily. e.g. by adding special data attributes or maybe by adding a component to the library. So I'm keeping this issue open to track that. It definitely feels like there should be an easier way to do a simple task like a default popper.

**Comment by KristofferStrube** [comment]
Hey @Liero,
I have had some more time to think about this. I don't think using CSS selectors is a good way to instantiate poppers in the context of a Blazor application as you wouldn't know the scope of the element that you find. This will cause problems if a popper is created for elements outside of the scope of a component if the component is closed and the instance is not `Destroy`'ed.

But I think the way to make this easier is by adding some predefined handlers for collections of `Poppers` that make the most common actions possible. This could include examples like the following. (I have not settled on the names yet)
## PopperGroup Example
This is a new class that can handle collections of element references for any type of element. The idea is then that the group will share a single tooltip so that if one popper gets activated then all other poppers in the group gets destroyed before creating the new one.
```html
@inject Popper Popper

@foreach(var item in Items) {
   <button type="button"
                  id="reference"
                  @ref=@PopperGroup.References[item.id]
                  aria-describedby="tooltip"
                  @onclick="_ => PopperGroup.Instantiate(item.id)">
      @item.text
   </button>
}

<div id="popper" @ref=@PopperGroup.Tooltip role="tooltip" style="height:50px;width:100px;">
   Popper
</div>

@code {
   protected List<(string text, int id)> Items = new()
      {
         ("this", 1),
         ("that", 2),
         ("and now this", 3),
      };

   protected PopperGroup PopperGroup { get; set; } = Popper.CreatePopperGroup(new Options())
}
```

## PopperComponent Example
This is a component that wraps the popper (tooltip) and adds some nice handlers for `Instantiate` and `Destroy`. With this we could do stuff like this:
```html
<button type="button" @ref=@ReferenceElement id="reference" aria-describedby="tooltip" @onclick="_ => ButtonClick()">
   Reference
</button>

<PopperComponent @ref=@PopperComponentInst @ReferenceElement=ReferenceElement >
   <div id="popper" role="tooltip" style="height:50px;width:100px;">
      Popper
   </div>
</PopperComponent>

@code {
   protected ElementReference ReferenceElement;
   
   protected PopperComponent PopperComponentInst;

   public async Task ButtonClick() {
      if (PopperComponentInst.IsActive) {
         await PopperComponentInst.Destroy();
      else  {
         await PopperComponentInst.Instantiate();
      }
   }
}
```

These are just some ideas and I'm not totally sure how to implement these features specifically, but do you think helper classes and components like these would help?

**Comment by KristofferStrube** [comment]
Hey @Liero,
I have decided that the next article I'll work on will be about scenarios with multiple types in Blazor Interop code like with this and some other places in this library. So I will work on this during the next couple of weeks and implement the suggested example that you had among others.

**Comment by KristofferStrube** [comment]
Hey @Liero,
In the newest release of the package I have added a `PopperComponent` which should simplify the use of the package.
